In [1]:
# Question 1 -->Arrays

import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    b = numpy.array(arr[::-1],float)
   
    return b

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


In [2]:
# Question 2  -->Shape and Reshape

import numpy as np
print(np.array(input().split(),int).reshape(3,3))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
# Question 3  --> Transpose and Flatten
import numpy

n, m = map(int, input().split())
array = numpy.array([input().strip().split() for _ in range(n)], int)
print (array.transpose())
print (array.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [8]:
# Question 4  -->concatenate

import numpy as np
a, b, c = map(int,input().split())
arrA = np.array([input().split() for _ in range(a)],int)
arrB = np.array([input().split() for _ in range(b)],int)
print(np.concatenate((arrA, arrB), axis = 0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [9]:
# Question 5 --> Zeros and Ones

import numpy

n = tuple(map(int,input().split()))
print(numpy.zeros(n, dtype = numpy.int))
print(numpy.ones(n, dtype = numpy.int))       


3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


C:\Users\HP\anaconda3\envs\Project1\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  
C:\Users\HP\anaconda3\envs\Project1\lib\site-packages\ipykernel_launcher.py:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for a

In [10]:
# QUestion 6  -->Eye and Identity

import numpy

n,m = map(int,input().strip().split())
print(str(numpy.eye(n, m, k=0)).replace('1',' 1').replace('0',' 0'))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [11]:
# Question 7  -->Array Mathemetics

import numpy
n,m = map(int, input().strip().split())
a, b = (numpy.array([input().split() for i in range(n)], dtype=int) for _ in range(2))

print(numpy.add(a, b))
print(numpy.subtract(a, b))
print(numpy.multiply(a, b))
print(a//b)
print(numpy.mod(a, b))
print(numpy.power(a, b))


1 4
1 2 4 5
1 2 4 8
[[ 2  4  8 13]]
[[ 0  0  0 -3]]
[[ 1  4 16 40]]
[[1 1 1 0]]
[[0 0 0 5]]
[[     1      4    256 390625]]


In [12]:
# Question 8  -->Floor, ceil and Rint

import numpy
numpy.set_printoptions(legacy='1.13')
a = numpy.array(input().split(),float)
print(numpy.floor(a))
print(numpy.ceil(a))  
print(numpy.rint(a))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [13]:
# Question 9 --> Sum and Prod

import numpy
n,m = map(int, input().split())
A = numpy.array([input().split() for i in range(n)],int)
print(numpy.prod(numpy.sum(A, axis=0), axis=0))


2 2
1 2
3 4
24


In [14]:
# Question 10  -->Min and max

import numpy as np
print(np.max(np.min(np.array([input().split() for _ in range(int(input().split()[0]))],int),axis=1)))

4 2
3 5
4 3
1 2
1 8
3


In [15]:
# Question 11  -->Mean, Var and Std

import numpy

n,m = map(int,input().split())
arr = []
for i in range(n):
    m = list(map(int, input().split()))
    arr.append(m)
arr = numpy.array(arr)

mean = numpy.mean(arr, axis = 1)
var = numpy.var(arr, axis = 0)
std = numpy.std(arr)

print(mean)
print(var)

rnd = numpy.around(std, 11)
print(rnd)

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


In [16]:
# Question 12 -->Dot and Cross

import numpy
n = int(input())
a = numpy.array([list(map(int,input().split()))for i in range(n)])
b = numpy.array([list(map(int,input().split()))for i in range(n)])
print(numpy.dot(a,b))


2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [17]:
# Question 13  -->Inner and Outer

import numpy

arr1=numpy.array([list(map(int,input().split()))])
arr2=numpy.array([list(map(int,input().split()))])
print(numpy.inner(arr1,arr2)[0][0])
print(numpy.outer(arr1,arr2))


0 1
2 3
3
[[0 0]
 [2 3]]


In [18]:
# Question 14  -->Polynomials

import numpy

b = list(map(float,input().split()))
a = input()
print(numpy.polyval(b,int(a)))

1.1 2 4 5
5
212.5


In [21]:
# Question 15  -->Linear Algebra

import numpy
n=int(input())
a=numpy.array([input().split() for _ in range(n)],float)
numpy.set_printoptions(legacy='1.13')
print(numpy.linalg.det(a))


2
1.1 1.1
1.1 1.1
0.0
